Repository Vegari-1/JobOfferService, pull requests merged in 2022-06, with the labels that each got.

#8 feat: CI/CD for running test and deploying package to GPR
  .github/workflows/build-test-package.yml
  release.config.js
Labels: configuration

#12 fix: Packaging configuration
  .github/workflows/build-test-package.yml
  JobOfferService/JobOfferService/JobOfferService.csproj
  release.config.js
Labels: bug, configuration

#18 feat: Publish Docker image to DockerHub
  .github/workflows/build-test-package.yml
  release.config.js
Labels: configuration

#20 fix: Change NuGet version fetching
  .github/workflows/build-test-package.yml
Labels: bug

#24 feat: add commit lint to pipeline
  .github/workflows/build-test-package.yml
Labels: configuration
